language: objective-c
osx_image: xcode9.3
before_install: 
- gem install cocoapods
- pod install
script: xcodebuild test -workspace Example/TermiNetwork.xcworkspace -scheme TermiNetwork-Example -destination 'platform=iOS Simulator,name=iPhone 8' CODE_SIGNING_REQUIRED=NO
