language: objective-c
before_install:
    - brew update
    - brew upgrade xctool
script: xctool -workspace Example/TermiNetwork.xcworkspace -scheme TermiNetwork-Example -sdk iphonesimulator run-tests 

